-- INSERT INTO owners (name) VALUES ("mugumogu");
-- INSERT INTO owners (name) VALUES ("Sophie");
-- INSERT INTO owners (name) VALUES ("Penny");
-- INSERT INTO cats (name, age, breed) VALUES ("Maru", 3, "Scottish Fold");
-- INSERT INTO cats (name, age, breed) VALUES ("Hana", 1, "Tabby");
-- INSERT INTO cats (name, age, breed) VALUES ("Nona", 4, "Tortoiseshell");
-- INSERT INTO cats (name, age, breed) VALUES ("Lil' Bub", 2, "perma-kitten");

-- INSERT INTO cat_owners (cat_id, owner_id) VALUES (3, 2);
-- INSERT INTO cat_owners (cat_id, owner_id) VALUES (3, 3);
-- INSERT INTO cat_owners (cat_id, owner_id) VALUES (1, 2);